<?php

/**
 * BaseTaxonomies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mark_id
 * @property enum $type
 * @property enum $status
 * @property Marks $Marks
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseTaxonomies extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('taxonomies');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('mark_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
    $this->hasColumn('type', 'enum', 8, array('type' => 'enum', 'length' => 8, 'values' => array(0 => 'tag', 1 => 'category'), 'notnull' => true));
    $this->hasColumn('status', 'enum', 7, array('type' => 'enum', 'length' => 7, 'values' => array(0 => 'draft', 1 => 'publish', 2 => 'deleted'), 'notnull' => true));
  }

  public function setUp()
  {
    $this->hasOne('Marks', array('local' => 'mark_id',
                                 'foreign' => 'id'));
  }
}