<?php

/**
 * BaseRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $taxonomy_id
 * @property Posts $Posts
 * @property Taxonomies $Taxonomies
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseRelations extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('relations');
    $this->hasColumn('post_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true));
    $this->hasColumn('taxonomy_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true));
  }

  public function setUp()
  {
    $this->hasOne('Posts', array('local' => 'post_id',
                                 'foreign' => 'id'));

    $this->hasOne('Taxonomies', array('local' => 'taxonomy_id',
                                      'foreign' => 'id'));
  }
}