<?php

/**
 * BaseMarks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $slug
 * @property enum $status
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseMarks extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('marks');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('title', 'string', 128, array('type' => 'string', 'length' => 128, 'notnull' => true));
    $this->hasColumn('slug', 'string', 128, array('type' => 'string', 'length' => 128, 'notnull' => true));
    $this->hasColumn('status', 'enum', 7, array('type' => 'enum', 'length' => 7, 'values' => array(0 => 'draft', 1 => 'publish', 2 => 'deleted'), 'notnull' => true));
  }

}